use_frameworks!

target 'VersaPlayer_Example' do
  pod 'VersaPlayer', :path => '../'

  target 'VersaPlayer_ExampleTests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1.2'
        end
    end
end
